// <auto-generated />
using System;
using ChatApp.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatApp.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531234926_MessageSeed")]
    partial class MessageSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatApp.Core.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MessageSend")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RecipientDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SenderDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "test-one",
                            DateRead = new DateTime(2024, 5, 30, 23, 49, 26, 315, DateTimeKind.Utc).AddTicks(2529),
                            IsActive = true,
                            MessageSend = new DateTime(2024, 5, 29, 23, 49, 26, 315, DateTimeKind.Utc).AddTicks(2539),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientDeleted = false,
                            RecipientId = 2,
                            RecipientUserName = "Mosaad",
                            SenderDeleted = false,
                            SenderId = 1,
                            SenderUserName = "Mohamed"
                        },
                        new
                        {
                            Id = 2,
                            Content = "test-two",
                            DateRead = new DateTime(2024, 5, 28, 23, 49, 26, 315, DateTimeKind.Utc).AddTicks(2544),
                            IsActive = false,
                            MessageSend = new DateTime(2024, 5, 27, 23, 49, 26, 315, DateTimeKind.Utc).AddTicks(2545),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientDeleted = false,
                            RecipientId = 1,
                            RecipientUserName = "Ahmed",
                            SenderDeleted = false,
                            SenderId = 2,
                            SenderUserName = "Khaled"
                        },
                        new
                        {
                            Id = 3,
                            Content = "test-three",
                            DateRead = new DateTime(2024, 6, 4, 23, 49, 26, 315, DateTimeKind.Utc).AddTicks(2548),
                            IsActive = true,
                            MessageSend = new DateTime(2024, 6, 3, 23, 49, 26, 315, DateTimeKind.Utc).AddTicks(2549),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientDeleted = false,
                            RecipientId = 1,
                            RecipientUserName = "Ali",
                            SenderDeleted = false,
                            SenderId = 2,
                            SenderUserName = "Hossam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
